CREATE TYPE "user_role" AS ENUM (
  'ADMIN',
  'INSTRUCTOR',
  'STUDENT'
);

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "academic_id" varchar UNIQUE,
  "username" varchar UNIQUE NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "first_name" varchar,
  "last_name" varchar,
  "password_hash" varchar NOT NULL,
  "role" user_role NOT NULL DEFAULT 'STUDENT',
  "is_active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "courses" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "course_code" varchar UNIQUE NOT NULL,
  "title" varchar NOT NULL,
  "department" varchar NOT NULL,
  "credit_count" integer NOT NULL,
  "syllabus_outline" text,
  "instructor_id" integer NOT NULL,
  "is_active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "enrollments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_id" integer NOT NULL,
  "course_id" integer NOT NULL,
  "enrolled_at" timestamp DEFAULT (now()),
  "is_active" boolean DEFAULT true
);

CREATE TABLE "modules" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "course_id" integer NOT NULL,
  "title" varchar NOT NULL,
  "order_index" integer NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "lessons" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "module_id" integer NOT NULL,
  "title" varchar NOT NULL,
  "content_markdown" text,
  "media_url" varchar,
  "order_index" integer NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "assignments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "course_id" integer NOT NULL,
  "title" varchar NOT NULL,
  "instructions" text,
  "release_at" timestamp NOT NULL,
  "deadline" timestamp NOT NULL,
  "max_points" numeric(5,2) NOT NULL,
  "allow_resubmissions" boolean DEFAULT false,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "submissions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "assignment_id" integer NOT NULL,
  "student_id" integer NOT NULL,
  "file_url" varchar NOT NULL,
  "submitted_at" timestamp DEFAULT (now()),
  "is_late" boolean DEFAULT false,
  "score" numeric(5,2),
  "feedback_markdown" text,
  "graded_by" integer,
  "graded_at" timestamp
);

CREATE TABLE "audit_logs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "actor_id" integer NOT NULL,
  "action_type" varchar NOT NULL,
  "target_entity" varchar NOT NULL,
  "timestamp" timestamp DEFAULT (now())
);

CREATE UNIQUE INDEX ON "enrollments" ("student_id", "course_id");

CREATE UNIQUE INDEX ON "submissions" ("assignment_id", "student_id");

COMMENT ON COLUMN "users"."academic_id" IS 'Institutional ID from roster';

COMMENT ON COLUMN "lessons"."media_url" IS 'Max 50MB attachment';

COMMENT ON COLUMN "submissions"."file_url" IS 'Max 25MB: .pdf, .zip, .docx';

COMMENT ON COLUMN "audit_logs"."action_type" IS 'e.g., USER_DEACTIVATE, GRADE_OVERRIDE, COURSE_DELETE';

COMMENT ON COLUMN "audit_logs"."target_entity" IS 'Entity name and identifier affected';

ALTER TABLE "courses" ADD FOREIGN KEY ("instructor_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "enrollments" ADD FOREIGN KEY ("student_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "enrollments" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "modules" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "lessons" ADD FOREIGN KEY ("module_id") REFERENCES "modules" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "assignments" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "submissions" ADD FOREIGN KEY ("assignment_id") REFERENCES "assignments" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "submissions" ADD FOREIGN KEY ("student_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "submissions" ADD FOREIGN KEY ("graded_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "audit_logs" ADD FOREIGN KEY ("actor_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

-- Defer constraint checking for INSERT
BEGIN;
SET CONSTRAINTS ALL DEFERRED;

INSERT INTO "users" ("id", "academic_id", "username", "email", "role")
VALUES
  (1, 'ADM-001', 'admin_root', 'admin@univ.edu', 'ADMIN'),
  (2, 'FAC-101', 'prof_smith', 'smith@univ.edu', 'INSTRUCTOR'),
  (3, 'STU-901', 'john_doe', 'john@univ.edu', 'STUDENT');
INSERT INTO "courses" ("id", "course_code", "title", "department", "credit_count", "instructor_id")
VALUES
  (101, 'CS-101', 'Introduction to Computer Science', 'CS Department', 3, 2);
INSERT INTO "enrollments" ("id", "student_id", "course_id")
VALUES
  (1, 3, 101);
INSERT INTO "assignments" ("id", "course_id", "title", "release_at", "deadline", "max_points")
VALUES
  (501, 101, 'Lab 1: Python Basics', '2026-10-01T09:00:00', '2026-10-15T23:59:59', 100);

SET CONSTRAINTS ALL IMMEDIATE;
COMMIT;