# Generated by Django 6.1.1 on 2026-09-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Designates whether this course is published to the public catalog.'),
        ),
    ]
