# Generated by Django 6.1.1 on 2026-09-24 22:22

import lms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_course_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, help_text='Short public course description shown in the catalog.', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Course cover image shown in the catalog. Recommended: 16:9 ratio.', null=True, upload_to='courses/thumbnails/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Estimated duration in minutes.'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='external_url',
            field=models.URLField(blank=True, help_text='External URL for LINK type lessons.', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('TEXT', 'Text / Markdown'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('PDF', 'PDF Document'), ('IMAGE', 'Image'), ('LINK', 'External Link')], default='TEXT', help_text='Type of lesson content', max_length=10),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content_markdown',
            field=models.TextField(blank=True, help_text='Rich text/markdown content for TEXT type lessons.', null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='media_file',
            field=models.FileField(blank=True, help_text='Upload: video (.mp4/.webm), audio (.mp3/.wav), PDF, or image. Max 50 MB.', null=True, upload_to='lessons/media/', validators=[lms.models.validate_lesson_media]),
        ),
    ]
